// web/frontend-vue/src/pages/Skills.vue
<script setup lang="ts">
// 技能页：getSkills 手风琴列表。迁移自 DevPilot Skills.tsx。
import { onMounted, ref } from 'vue'
import { getSkills, type Skill } from '../api'

const skills = ref<Skill[]>([])
const open = ref<Record<string, boolean>>({})
const err = ref('')

onMounted(async () => {
  try {
    skills.value = await getSkills()
  } catch (e) {
    err.value = String(e)
  }
})

function toggle(name: string): void {
  open.value[name] = !open.value[name]
}
</script>

<template>
  <div class="skills-page">
    <header class="skills-header">
      <h1 class="grad-bili-text">技能</h1>
      <span class="sub">已注册的 AI Skill 清单</span>
    </header>

    <div v-if="err" class="err-box">加载失败：{{ err }}</div>

    <div class="skill-list">
      <div v-for="s in skills" :key="s.name" class="skill-card">
        <button class="skill-head" @click="toggle(s.name)">
          <span class="skill-icon">{{ s.name.slice(0, 2).toUpperCase() }}</span>
          <span class="skill-name">{{ s.name }}</span>
          <span class="spec-count">{{ s.specs.length }} specs</span>
          <span class="arrow" :class="{ open: open[s.name] }">▶</span>
        </button>
        <div v-if="open[s.name]" class="spec-list">
          <div v-for="(sp, i) in s.specs" :key="i" class="spec-card">
            <div class="spec-name">{{ sp.name }}</div>
            <div class="spec-desc">{{ sp.description }}</div>
            <div class="spec-schema-label">Schema</div>
            <pre class="spec-schema">{{ JSON.stringify(sp.schema, null, 2) }}</pre>
          </div>
        </div>
      </div>
      <div v-if="skills.length === 0 && !err" class="empty">无已注册技能</div>
    </div>
  </div>
</template>

<style scoped>
.skills-page {
  height: 100%;
  overflow-y: auto;
  padding: 24px;
}
.skills-header {
  display: flex;
  align-items: baseline;
  gap: 12px;
  margin-bottom: 24px;
}
.skills-header h1 {
  font-size: 20px;
  margin: 0;
}
.sub {
  font-size: 12px;
  color: var(--cf-text-3);
}
.err-box {
  padding: 12px 16px;
  border-radius: 10px;
  background: rgba(242, 93, 89, 0.1);
  border: 1px solid var(--cf-red);
  color: var(--cf-red);
  font-size: 13px;
  margin-bottom: 16px;
}
.skill-list {
  display: flex;
  flex-direction: column;
  gap: 10px;
}
.skill-card {
  border: 1px solid var(--cf-border);
  border-radius: var(--cf-radius-md);
  background: var(--cf-card);
  overflow: hidden;
}
.skill-head {
  width: 100%;
  display: flex;
  align-items: center;
  gap: 12px;
  padding: 14px 18px;
  background: none;
  border: none;
  cursor: pointer;
  color: var(--cf-text-1);
  font-size: 14px;
}
.skill-head:hover {
  background: var(--cf-hover);
}
.skill-icon {
  width: 32px;
  height: 32px;
  border-radius: 8px;
  background: linear-gradient(135deg, var(--cf-bili-blue), var(--cf-bili-pink));
  color: #fff;
  font-size: 12px;
  font-weight: 700;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
}
.skill-name {
  font-weight: 600;
  font-family: ui-monospace, monospace;
  color: var(--cf-bili-blue);
}
.spec-count {
  font-size: 12px;
  color: var(--cf-text-3);
  margin-left: auto;
}
.arrow {
  font-size: 10px;
  color: var(--cf-text-3);
  transition: transform 0.15s;
}
.arrow.open {
  transform: rotate(90deg);
}
.spec-list {
  padding: 0 18px 16px;
  display: flex;
  flex-direction: column;
  gap: 12px;
  border-top: 1px solid var(--cf-border);
}
.spec-card {
  padding: 12px 16px;
  border-radius: 8px;
  background: var(--cf-bg);
  border: 1px solid var(--cf-border-soft);
}
.spec-name {
  font-family: ui-monospace, monospace;
  font-size: 13px;
  color: var(--cf-bili-blue);
  font-weight: 600;
}
.spec-desc {
  font-size: 12px;
  color: var(--cf-text-3);
  margin: 4px 0 8px;
}
.spec-schema-label {
  font-size: 10px;
  text-transform: uppercase;
  color: var(--cf-text-4);
  margin-bottom: 4px;
}
.spec-schema {
  margin: 0;
  padding: 8px 12px;
  border-radius: 6px;
  background: var(--cf-sidebar);
  font-size: 11px;
  font-family: ui-monospace, monospace;
  color: var(--cf-text-2);
  overflow-x: auto;
}
.empty {
  color: var(--cf-text-4);
  font-size: 14px;
  padding: 40px 0;
  text-align: center;
}
</style>

// web/frontend/src/pages/Skills.tsx
import { useEffect, useState } from "react";
import { getSkills, type Skill } from "../api";

export default function SkillsPage() {
  const [skills, setSkills] = useState<Skill[] | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [open, setOpen] = useState<Record<string, boolean>>({});

  useEffect(() => {
    getSkills()
      .then(setSkills)
      .catch((err) => setError(err instanceof Error ? err.message : String(err)));
  }, []);

  function toggle(name: string) {
    setOpen((p) => ({ ...p, [name]: !p[name] }));
  }

  return (
    <div className="h-full flex flex-col">
      <header className="px-6 py-4 border-b border-slate-800">
        <h1 className="text-lg font-semibold">Skills</h1>
        <p className="text-xs text-slate-500">Registered skills and their tool specs.</p>
      </header>
      <div className="flex-1 overflow-auto px-6 py-6">
        {error && (
          <div className="px-3 py-2 rounded-md bg-rose-500/10 border border-rose-500/30 text-rose-300 text-sm">
            {error}
          </div>
        )}
        {!skills && !error && (
          <div className="text-slate-600 text-sm">Loading skills…</div>
        )}
        {skills && skills.length === 0 && (
          <div className="text-slate-600 text-sm">No skills registered.</div>
        )}
        <div className="grid gap-3">
          {skills?.map((skill) => {
            const isOpen = !!open[skill.name];
            return (
              <div
                key={skill.name}
                className="rounded-lg border border-slate-800 bg-slate-900 overflow-hidden"
              >
                <button
                  onClick={() => toggle(skill.name)}
                  className="w-full flex items-center justify-between px-4 py-3 text-left hover:bg-slate-800/60"
                >
                  <div className="flex items-center gap-3">
                    <span className="h-7 w-7 rounded-md bg-indigo-500/15 text-indigo-300 flex items-center justify-center text-xs font-mono">
                      {skill.name.slice(0, 2)}
                    </span>
                    <div>
                      <div className="text-sm font-medium text-slate-100">{skill.name}</div>
                      <div className="text-[11px] text-slate-500">
                        {skill.specs.length} spec{skill.specs.length === 1 ? "" : "s"}
                      </div>
                    </div>
                  </div>
                  <span className={`text-slate-500 transition-transform ${isOpen ? "rotate-90" : ""}`}>
                    ▶
                  </span>
                </button>
                {isOpen && (
                  <div className="px-4 pb-4 pt-1 space-y-3 border-t border-slate-800">
                    {skill.specs.map((spec) => (
                      <div key={spec.name} className="rounded-md bg-slate-950 border border-slate-800 p-3">
                        <div className="flex items-center gap-2">
                          <span className="font-mono text-sm text-indigo-300">{spec.name}</span>
                        </div>
                        <p className="text-xs text-slate-400 mt-1">{spec.description}</p>
                        <div className="mt-2">
                          <div className="text-[10px] uppercase tracking-wider text-slate-500 mb-1">
                            Schema
                          </div>
                          <pre className="text-[11px] text-slate-300 overflow-auto bg-slate-900 rounded p-2">
                            {JSON.stringify(spec.schema, null, 2)}
                          </pre>
                        </div>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
}
