// web/frontend/src/components/FlowGraph.tsx
import { useEffect, useMemo, useState } from "react";
import dagre from "dagre";
import {
  ReactFlow,
  Background,
  Controls,
  MiniMap,
  Handle,
  Position,
  useNodesState,
  useEdgesState,
  type Node,
  type Edge,
} from "@xyflow/react";
import "@xyflow/react/dist/style.css";

// ============================================================================
// 动态图形流：根据 planner 生成的步骤计划动态画图
// 与固定节点图不同，节点数量/名称由 LLM 规划决定——
// "总结资讯"3 步、"写函数"1 步，图随任务而变。
// ============================================================================

/** 节点运行状态：idle 等待 / running 运行中 / done 完成 / error 出错 */
type NodeStatus = "idle" | "running" | "done" | "error";

/** planner 生成的单步计划（与后端 plan 帧的 step 结构对齐） */
export interface PlanStep {
  id: string;
  name: string;
  description: string;
  output: string;
  needs_search: boolean;
}

/** DevNode 自定义节点的 data 字段 */
interface DevNodeData {
  label: string;
  status: NodeStatus;
  kind: "planner" | "step";
  needsSearch?: boolean;
  [key: string]: unknown;
}

/** FlowGraph 接收的节点状态更新项（来自 node 帧） */
export interface NodeUpdate {
  node_id: string;
  status: NodeStatus;
}

interface FlowGraphProps {
  /** 节点状态更新列表，监听后写入对应 node.data.status */
  nodeUpdates?: NodeUpdate[];
  /** planner 生成的步骤计划：收到后据此动态重建节点图 */
  plan?: PlanStep[] | null;
}

// ============================================================================
// dagre 自动布局
// ============================================================================

function getLayoutedElements<N extends Node, E extends Edge>(
  nodes: N[],
  edges: E[],
  direction: "LR" | "TB" = "LR",
): { nodes: N[]; edges: E[] } {
  const g = new dagre.graphlib.Graph();
  g.setDefaultEdgeLabel(() => ({}));
  g.setGraph({ rankdir: direction, nodesep: 40, ranksep: 90 });
  const nodeWidth = 150;
  const nodeHeight = 52;
  nodes.forEach((node) => g.setNode(node.id, { width: nodeWidth, height: nodeHeight }));
  edges.forEach((edge) => g.setEdge(edge.source, edge.target));
  dagre.layout(g);
  const layoutedNodes = nodes.map((node) => {
    const pos = g.node(node.id);
    return { ...node, position: { x: pos.x - nodeWidth / 2, y: pos.y - nodeHeight / 2 } };
  });
  return { nodes: layoutedNodes, edges };
}

// ============================================================================
// 自定义节点组件 DevNode
// 深色卡片 + 状态指示圆点 + 搜索图标 + 左右 Handle
// ============================================================================

function statusClasses(status: NodeStatus) {
  switch (status) {
    case "running":
      return { border: "border-amber-500", text: "text-amber-300", dot: "bg-amber-400", pulse: "animate-pulse" };
    case "done":
      return { border: "border-emerald-500", text: "text-emerald-300", dot: "bg-emerald-400", pulse: "" };
    case "error":
      return { border: "border-rose-500", text: "text-rose-300", dot: "bg-rose-400", pulse: "" };
    default:
      return { border: "border-slate-700", text: "text-slate-500", dot: "bg-slate-600", pulse: "" };
  }
}

function DevNode({ data }: { id: string; data: DevNodeData }) {
  const { label, status, kind, needsSearch } = data;
  const s = statusClasses(status);
  return (
    <div
      className={`min-w-[140px] rounded-lg border-2 bg-slate-900 px-3 py-2 ${s.border} ${s.pulse}`}
    >
      <Handle type="target" position={Position.Left} style={{ background: "#475569", width: 6, height: 6, border: "none" }} />
      <div className="flex items-center gap-2">
        <span className={`h-2 w-2 shrink-0 rounded-full ${s.dot}`} />
        <span className={`font-medium text-xs ${s.text}`}>{label}</span>
        {/* 联网搜索标记：planner 标记或 step 的 needs_search */}
        {needsSearch && (
          <span className="ml-auto text-[10px] text-sky-400" title="联网搜索">
            🌐
          </span>
        )}
        {kind === "planner" && (
          <span className="ml-auto text-[10px] text-violet-400" title="规划">
            ⛳
          </span>
        )}
      </div>
      <Handle type="source" position={Position.Right} style={{ background: "#475569", width: 6, height: 6, border: "none" }} />
    </div>
  );
}

const nodeTypes = { devNode: DevNode };

// ============================================================================
// 主组件 FlowGraph（动态）
// ============================================================================

/**
 * 动态图形流：收到 plan 帧的步骤列表后，构建 [planner, step1, step2, ...] 节点，
 * 用 dagre 布局，边连成顺序链 planner→step1→step2→...。
 * node 帧按 node_id 更新对应节点状态色。
 */
export default function FlowGraph({ nodeUpdates, plan }: FlowGraphProps) {
  // 据当前 plan 动态生成初始节点/边。plan 变化（新对话）时重建图。
  const { nodes: baseNodes, edges: baseEdges } = useMemo(() => {
    if (!plan || plan.length === 0) {
      // 无 plan：占位单节点（等待规划）。
      return getLayoutedElements(
        [{ id: "planner", type: "devNode", data: { label: "Planner", status: "idle" as NodeStatus, kind: "planner" as const }, position: { x: 0, y: 0 } }] as Node<DevNodeData>[],
        [] as Edge[],
      );
    }
    const plannerNode: Node<DevNodeData> = {
      id: "planner",
      type: "devNode",
      data: { label: "Planner", status: "idle", kind: "planner" },
      position: { x: 0, y: 0 },
    };
    const stepNodes: Node<DevNodeData>[] = plan.map((s) => ({
      id: s.id,
      type: "devNode",
      data: { label: s.name, status: "idle", kind: "step", needsSearch: s.needs_search },
      position: { x: 0, y: 0 },
    }));
    // 边：planner→step1→step2→...
    const edges: Edge[] = [];
    edges.push({ id: "planner-step1", source: "planner", target: plan[0].id });
    for (let i = 0; i < plan.length - 1; i++) {
      edges.push({ id: `${plan[i].id}-${plan[i + 1].id}`, source: plan[i].id, target: plan[i + 1].id });
    }
    return getLayoutedElements([plannerNode, ...stepNodes], edges);
  }, [plan]);

  const [nodes, setNodes, onNodesChange] = useNodesState(baseNodes);
  const [edges, , onEdgesChange] = useEdgesState(baseEdges);

  // plan 变化时重置图（新对话）。
  const [planVersion, setPlanVersion] = useState(0);
  useEffect(() => {
    setNodes(baseNodes);
    setPlanVersion((v) => v + 1);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [plan]);

  // 监听 nodeUpdates：按 node_id 更新对应节点状态（取最新）。
  useEffect(() => {
    if (!nodeUpdates || nodeUpdates.length === 0) return;
    setNodes((nds) =>
      nds.map((n) => {
        let upd: NodeUpdate | undefined;
        for (let i = nodeUpdates.length - 1; i >= 0; i--) {
          if (nodeUpdates[i].node_id === n.id) {
            upd = nodeUpdates[i];
            break;
          }
        }
        if (!upd) return n;
        return { ...n, data: { ...(n.data as DevNodeData), status: upd.status } };
      }),
    );
  }, [nodeUpdates, setNodes]);

  return (
    <ReactFlow
      nodes={nodes}
      edges={edges}
      onNodesChange={onNodesChange}
      onEdgesChange={onEdgesChange}
      nodeTypes={nodeTypes}
      nodesDraggable={false}
      nodesConnectable={false}
      elementsSelectable={false}
      fitView
      proOptions={{ hideAttribution: true }}
      style={{ height: "100%" }}
      className="bg-slate-950"
      key={planVersion}
    >
      <Background gap={16} size={1} color="#1e293b" />
      <Controls showInteractive={false} className="!bg-slate-900 !border-slate-800" />
      <MiniMap
        pannable
        zoomable
        nodeColor={(n) => {
          const data = n.data as DevNodeData;
          if (data.status === "running") return "#f59e0b";
          if (data.status === "done") return "#10b981";
          if (data.status === "error") return "#f43f5e";
          return "#334155";
        }}
        maskColor="rgba(2, 6, 23, 0.7)"
        className="!bg-slate-900 !border-slate-800"
      />
    </ReactFlow>
  );
}

// web/frontend-vue/src/components/FlowGraph.vue
<script setup lang="ts">
// 动态图形流：收到 plan 帧的步骤列表后动态建图 [planner, step1, step2, ...]，
// dagre 布局，边连顺序链 planner→step1→step2→...。node 帧按 node_id 更新状态色。
// 迁移自 DevPilot web/frontend/src/components/FlowGraph.tsx（@xyflow/react → @vue-flow/core）。
import { ref, watch, nextTick } from 'vue'
import { VueFlow, Handle, Position, useVueFlow } from '@vue-flow/core'
import { Background } from '@vue-flow/background'
import { Controls } from '@vue-flow/controls'
import { MiniMap } from '@vue-flow/minimap'
import dagre from 'dagre'
import '@vue-flow/core/dist/style.css'
import '@vue-flow/core/dist/theme-default.css'
import '@vue-flow/controls/dist/style.css'
import '@vue-flow/minimap/dist/style.css'
import type { PlanStep, NodeUpdate, NodeStatus } from '../api'

interface DevNodeData {
  label: string
  status: NodeStatus
  kind: 'planner' | 'step'
  needsSearch?: boolean
}

interface FlowNode {
  id: string
  type: string
  position: { x: number; y: number }
  data: DevNodeData
}

interface FlowEdge {
  id: string
  source: string
  target: string
}

const props = defineProps<{
  plan?: PlanStep[] | null
  nodeUpdates?: NodeUpdate[]
}>()

const nodes = ref<FlowNode[]>([])
const edges = ref<FlowEdge[]>([])

const { onInit, fitView } = useVueFlow()

// 全图适配视口：plan 变化重建图后，让 vue-flow 自己把所有节点缩放到可见范围，
// 保证整条链不拖动也能看全。planner 由 dagre TB 布局自然落在最上方。
// 加 requestAnimationFrame 确保节点 DOM 渲染完再 fit（vue-flow 异步处理 prop→内部 nodes）。
function fitGraph() {
  fitView({ padding: 0.25, maxZoom: 1.0 })
}

onInit(() => {
  nextTick(() => requestAnimationFrame(fitGraph))
})

function statusStyle(status: NodeStatus) {
  switch (status) {
    case 'running':
      return { border: '#f59e0b', dot: '#fbbf24', text: '#fcd34d' }
    case 'done':
      return { border: '#10b981', dot: '#34d399', text: '#6ee7b7' }
    case 'error':
      return { border: '#f43f5e', dot: '#fb7185', text: '#fda4af' }
    default:
      return { border: '#334155', dot: '#475569', text: '#64748b' }
  }
}

function getLayouted(ns: FlowNode[], es: FlowEdge[], direction: 'LR' | 'TB' = 'TB') {
  const g = new dagre.graphlib.Graph()
  g.setDefaultEdgeLabel(() => ({}))
  g.setGraph({ rankdir: direction, nodesep: 40, ranksep: 90 })
  const w = 150
  const h = 52
  ns.forEach((n) => g.setNode(n.id, { width: w, height: h }))
  es.forEach((e) => g.setEdge(e.source, e.target))
  dagre.layout(g)
  return {
    nodes: ns.map((n) => {
      const pos = g.node(n.id)
      return { ...n, position: { x: pos.x - w / 2, y: pos.y - h / 2 } }
    }),
    edges: es,
  }
}

function buildGraph(plan: PlanStep[] | null | undefined) {
  if (!plan || plan.length === 0) {
    const single: FlowNode = {
      id: 'planner',
      type: 'devNode',
      data: { label: 'Planner', status: 'idle', kind: 'planner' },
      position: { x: 0, y: 0 },
    }
    const r = getLayouted([single], [])
    nodes.value = r.nodes
    edges.value = r.edges
    return
  }
  const plannerNode: FlowNode = {
    id: 'planner',
    type: 'devNode',
    data: { label: 'Planner', status: 'idle', kind: 'planner' },
    position: { x: 0, y: 0 },
  }
  const stepNodes: FlowNode[] = plan.map((s) => ({
    id: s.id,
    type: 'devNode',
    data: { label: s.name, status: 'idle', kind: 'step', needsSearch: s.needs_search },
    position: { x: 0, y: 0 },
  }))
  const es: FlowEdge[] = []
  es.push({ id: 'planner-step1', source: 'planner', target: plan[0].id })
  for (let i = 0; i < plan.length - 1; i++) {
    es.push({ id: `${plan[i].id}-${plan[i + 1].id}`, source: plan[i].id, target: plan[i + 1].id })
  }
  const r = getLayouted([plannerNode, ...stepNodes], es)
  nodes.value = r.nodes
  edges.value = r.edges
}

watch(
  () => props.plan,
  (p) => {
    buildGraph(p)
    nextTick(() => requestAnimationFrame(fitGraph))
  },
  { immediate: true },
)

watch(
  () => props.nodeUpdates,
  (ups) => {
    if (!ups || ups.length === 0) return
    // 每个 node 取最新 update（反向查找，与原 React 版一致）。
    const latest = new Map<string, NodeStatus>()
    for (const u of ups) latest.set(u.node_id, u.status)
    nodes.value = nodes.value.map((n) => {
      const st = latest.get(n.id)
      if (!st) return n
      return { ...n, data: { ...n.data, status: st } }
    })
  },
  { deep: true },
)

function miniMapColor(n: { data?: DevNodeData }): string {
  const d = n.data
  if (!d) return '#334155'
  if (d.status === 'running') return '#f59e0b'
  if (d.status === 'done') return '#10b981'
  if (d.status === 'error') return '#f43f5e'
  return '#334155'
}
</script>

<template>
  <div class="flow-graph">
    <VueFlow
      :nodes="nodes"
      :edges="edges"
      :nodes-draggable="false"
      :nodes-connectable="false"
      :elements-selectable="false"
      :default-edge-options="{ type: 'smoothstep' }"
    >
      <Background :gap="16" :size="1" pattern-color="#1e293b" />
      <Controls :show-interactive="false" />
      <MiniMap pannable zoomable :node-color="miniMapColor" mask-color="rgba(2, 6, 23, 0.7)" />
      <template #node-devNode="{ data }">
        <div
          class="dev-node"
          :style="{ borderColor: statusStyle(data.status).border }"
          :class="{ pulse: data.status === 'running' }"
        >
          <Handle type="target" :position="Position.Top" :style="{ background: '#475569', width: '6px', height: '6px', border: 'none' }" />
          <div class="dev-row">
            <span class="dot" :style="{ background: statusStyle(data.status).dot }" />
            <span class="label" :style="{ color: statusStyle(data.status).text }">{{ data.label }}</span>
            <span v-if="data.needsSearch" class="badge" title="联网搜索">🌐</span>
            <span v-if="data.kind === 'planner'" class="badge planner" title="规划">⛳</span>
          </div>
          <Handle type="source" :position="Position.Bottom" :style="{ background: '#475569', width: '6px', height: '6px', border: 'none' }" />
        </div>
      </template>
    </VueFlow>
  </div>
</template>

<style scoped>
.flow-graph {
  height: 100%;
  background: #0f1115;
}
.dev-node {
  min-width: 140px;
  border: 2px solid #334155;
  background: #1c1f24;
  border-radius: 10px;
  padding: 8px 12px;
}
.dev-node.pulse {
  animation: devpulse 1.5s infinite;
}
@keyframes devpulse {
  0%,
  100% {
    box-shadow: 0 0 0 0 rgba(245, 158, 11, 0.4);
  }
  50% {
    box-shadow: 0 0 0 6px rgba(245, 158, 11, 0);
  }
}
.dev-row {
  display: flex;
  align-items: center;
  gap: 8px;
}
.dot {
  width: 8px;
  height: 8px;
  border-radius: 50%;
  flex-shrink: 0;
}
.label {
  font-size: 12px;
  font-weight: 500;
}
.badge {
  margin-left: auto;
  font-size: 11px;
}
.badge.planner {
  color: #a78bfa;
}
</style>
