// web/frontend/src/pages/Run.tsx
import { FormEvent, useEffect, useRef, useState } from "react";
import {
  RunSocket,
  type AuditEntry,
  type BlackboardData,
  type ApprovalRequest,
  type DoneSummary,
} from "../api";

const EVENT_COLORS: Record<string, string> = {
  agent_step: "text-indigo-300 border-indigo-500/40 bg-indigo-500/10",
  llm_call: "text-violet-300 border-violet-500/40 bg-violet-500/10",
  tool_call: "text-emerald-300 border-emerald-500/40 bg-emerald-500/10",
  approval: "text-amber-300 border-amber-500/40 bg-amber-500/10",
};

type Status = "idle" | "connecting" | "running" | "awaiting_approval" | "done" | "error";

export default function RunPage() {
  const [task, setTask] = useState("");
  const [status, setStatus] = useState<Status>("idle");
  const [audit, setAudit] = useState<AuditEntry[]>([]);
  const [blackboard, setBlackboard] = useState<BlackboardData | null>(null);
  const [approval, setApproval] = useState<ApprovalRequest | null>(null);
  const [summary, setSummary] = useState<DoneSummary | null>(null);
  const [decisionComment, setDecisionComment] = useState("");
  const [editArgs, setEditArgs] = useState("{}");
  const socketRef = useRef<RunSocket | null>(null);

  useEffect(() => {
    return () => socketRef.current?.close();
  }, []);

  function reset() {
    setAudit([]);
    setBlackboard(null);
    setApproval(null);
    setSummary(null);
    setDecisionComment("");
    setEditArgs("{}");
  }

  function onStart(e: FormEvent) {
    e.preventDefault();
    if (!task.trim()) return;
    reset();
    setStatus("connecting");

    const sock = new RunSocket({
      onOpen: () => {
        setStatus("running");
        sock.send({ task });
      },
      onFrame: (frame) => {
        switch (frame.type) {
          case "audit":
            setAudit((prev) => [...prev, frame.entry]);
            break;
          case "blackboard":
            setBlackboard(frame.data);
            break;
          case "approval_request":
            setApproval({
              action: frame.action,
              args: frame.args,
              reason: frame.reason,
            });
            setEditArgs(JSON.stringify(frame.args, null, 2));
            setStatus("awaiting_approval");
            break;
          case "done":
            setBlackboard(frame.blackboard);
            setSummary(frame.summary);
            setApproval(null);
            setStatus("done");
            socketRef.current?.close();
            break;
        }
      },
      onClose: () => {
        if (status !== "done") setStatus((s) => (s === "awaiting_approval" ? s : "idle"));
      },
      onError: () => setStatus("error"),
    });
    socketRef.current = sock;
    sock.connect();
  }

  function sendDecision(decision: "approve" | "reject" | "edit") {
    let args: Record<string, unknown> = {};
    if (decision === "edit") {
      try {
        args = JSON.parse(editArgs);
      } catch {
        alert("Edit args is not valid JSON");
        return;
      }
    }
    socketRef.current?.send({ decision, comment: decisionComment, args });
    setApproval(null);
    setDecisionComment("");
    setStatus("running");
  }

  return (
    <div className="h-full flex flex-col">
      <header className="px-6 py-4 border-b border-slate-800">
        <h1 className="text-lg font-semibold">Run</h1>
        <p className="text-xs text-slate-500">
          Stream an agent run over WebSocket with a live audit timeline and blackboard.
        </p>
      </header>

      <form onSubmit={onStart} className="px-6 py-4 border-b border-slate-800 flex gap-3 items-center">
        <input
          value={task}
          onChange={(e) => setTask(e.target.value)}
          placeholder="Describe a task for the agent…"
          className="flex-1 px-4 py-2.5 rounded-md bg-slate-900 border border-slate-700 text-sm focus:outline-none focus:border-indigo-500"
        />
        <button
          type="submit"
          disabled={!task.trim() || status === "running" || status === "connecting" || status === "awaiting_approval"}
          className="px-5 py-2.5 rounded-md bg-indigo-600 hover:bg-indigo-500 disabled:bg-slate-800 disabled:text-slate-600 text-white text-sm font-medium"
        >
          {status === "running" || status === "connecting" ? "Running…" : "Start"}
        </button>
        <StatusBadge status={status} />
      </form>

      <div className="flex-1 grid grid-cols-1 lg:grid-cols-[1fr_1fr] gap-px bg-slate-800 overflow-hidden">
        <Timeline audit={audit} />
        <BlackboardPanel
          blackboard={blackboard}
          summary={summary}
          status={status}
        />
      </div>

      {approval && (
        <ApprovalModal
          approval={approval}
          comment={decisionComment}
          setComment={setDecisionComment}
          editArgs={editArgs}
          setEditArgs={setEditArgs}
          onDecide={sendDecision}
        />
      )}
    </div>
  );
}

function StatusBadge({ status }: { status: Status }) {
  const map: Record<Status, string> = {
    idle: "bg-slate-800 text-slate-400",
    connecting: "bg-amber-500/15 text-amber-300",
    running: "bg-indigo-500/15 text-indigo-300",
    awaiting_approval: "bg-amber-500/15 text-amber-300",
    done: "bg-emerald-500/15 text-emerald-300",
    error: "bg-rose-500/15 text-rose-300",
  };
  const label = status.replace(/_/g, " ");
  return (
    <span className={`px-3 py-1 rounded-full text-[11px] font-medium ${map[status]}`}>
      {label}
    </span>
  );
}

function Timeline({ audit }: { audit: AuditEntry[] }) {
  const ref = useRef<HTMLDivElement>(null);
  useEffect(() => {
    ref.current?.scrollTo({ top: ref.current.scrollHeight });
  }, [audit]);

  return (
    <section className="flex flex-col bg-slate-950 min-h-0">
      <div className="px-4 py-2 text-xs uppercase tracking-wider text-slate-500 border-b border-slate-800">
        Audit Timeline
      </div>
      <div ref={ref} className="flex-1 overflow-auto px-4 py-3 space-y-2">
        {audit.length === 0 && (
          <div className="text-slate-600 text-sm py-6 text-center">
            Waiting for audit frames…
          </div>
        )}
        {audit.map((entry, i) => (
          <div
            key={i}
            className={`px-3 py-2 rounded-md border text-xs ${
              EVENT_COLORS[entry.event] ?? "text-slate-300 border-slate-700 bg-slate-900"
            }`}
          >
            <div className="flex items-center justify-between gap-2">
              <span className="font-mono uppercase tracking-wider">{entry.event}</span>
              <span className="text-slate-500 text-[10px]">{entry.actor}</span>
            </div>
            <div className="mt-1 text-slate-400 text-[11px] break-words">
              {JSON.stringify(entry.detail)}
            </div>
            <div className="mt-1 text-slate-600 text-[10px] font-mono">
              {entry.timestamp} · {entry.trace_id}
            </div>
          </div>
        ))}
      </div>
    </section>
  );
}

function BlackboardPanel({
  blackboard,
  summary,
  status,
}: {
  blackboard: BlackboardData | null;
  summary: DoneSummary | null;
  status: Status;
}) {
  const empty = !blackboard;
  return (
    <section className="flex flex-col bg-slate-950 min-h-0 overflow-auto">
      <div className="px-4 py-2 text-xs uppercase tracking-wider text-slate-500 border-b border-slate-800">
        Blackboard
      </div>
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-px bg-slate-800 flex-1">
        <Panel title="Plan">
          {empty || blackboard.plan.length === 0 ? (
            <Empty />
          ) : (
            <ol className="list-decimal list-inside space-y-1 text-sm text-slate-300">
              {blackboard.plan.map((step, i) => (
                <li key={i}>{step}</li>
              ))}
            </ol>
          )}
        </Panel>
        <Panel title="Code Diff" mono>
          {empty || !blackboard.code_diff ? <Empty /> : (
            <pre className="text-[11px] text-emerald-300 whitespace-pre-wrap break-all">
              {blackboard.code_diff}
            </pre>
          )}
        </Panel>
        <Panel title="Review">
          {empty || !blackboard.review ? <Empty /> : (
            <pre className="text-sm text-slate-300 whitespace-pre-wrap">{blackboard.review}</pre>
          )}
        </Panel>
        <Panel title="Test Result">
          {empty || !blackboard.test_result ? <Empty /> : (
            <pre className="text-sm text-slate-300 whitespace-pre-wrap">{blackboard.test_result}</pre>
          )}
        </Panel>
      </div>
      {status === "done" && summary && (
        <div className="px-4 py-3 border-t border-slate-800 bg-slate-900/60 text-xs">
          <div className="text-slate-400 mb-1">
            Done · <span className="text-emerald-300">{summary.total_events}</span> events
          </div>
          <div className="flex flex-wrap gap-2">
            {Object.entries(summary.by_event).map(([k, v]) => (
              <span key={k} className="px-2 py-0.5 rounded bg-slate-800 text-slate-400 text-[10px]">
                {k}: {v}
              </span>
            ))}
          </div>
        </div>
      )}
    </section>
  );
}

function Panel({
  title,
  children,
  mono,
}: {
  title: string;
  children: React.ReactNode;
  mono?: boolean;
}) {
  return (
    <div className="bg-slate-950 p-3 flex flex-col min-h-0">
      <div className="text-[10px] uppercase tracking-wider text-slate-500 mb-2">{title}</div>
      <div className={`flex-1 overflow-auto ${mono ? "font-mono" : ""}`}>{children}</div>
    </div>
  );
}

function Empty() {
  return <div className="text-slate-600 text-xs">—</div>;
}

function ApprovalModal({
  approval,
  comment,
  setComment,
  editArgs,
  setEditArgs,
  onDecide,
}: {
  approval: ApprovalRequest;
  comment: string;
  setComment: (v: string) => void;
  editArgs: string;
  setEditArgs: (v: string) => void;
  onDecide: (d: "approve" | "reject" | "edit") => void;
}) {
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4">
      <div className="w-full max-w-lg rounded-xl border border-slate-700 bg-slate-900 shadow-2xl">
        <div className="px-5 py-4 border-b border-slate-800">
          <div className="flex items-center gap-2">
            <span className="px-2 py-0.5 rounded bg-amber-500/15 text-amber-300 text-[10px] uppercase tracking-wider">
              Approval Required
            </span>
            <span className="font-mono text-sm text-slate-200">{approval.action}</span>
          </div>
        </div>
        <div className="px-5 py-4 space-y-3">
          <div>
            <div className="text-[10px] uppercase tracking-wider text-slate-500 mb-1">Reason</div>
            <div className="text-sm text-slate-300">{approval.reason}</div>
          </div>
          <div>
            <div className="text-[10px] uppercase tracking-wider text-slate-500 mb-1">Args</div>
            <pre className="px-3 py-2 rounded bg-slate-950 border border-slate-800 text-[11px] text-slate-300 overflow-auto max-h-40">
              {JSON.stringify(approval.args, null, 2)}
            </pre>
          </div>
          <div>
            <label className="text-[10px] uppercase tracking-wider text-slate-500 block mb-1">
              Comment
            </label>
            <input
              value={comment}
              onChange={(e) => setComment(e.target.value)}
              placeholder="optional note…"
              className="w-full px-3 py-2 rounded-md bg-slate-950 border border-slate-700 text-sm focus:outline-none focus:border-indigo-500"
            />
          </div>
          <div>
            <label className="text-[10px] uppercase tracking-wider text-slate-500 block mb-1">
              Edit args (JSON, used only on "Edit")
            </label>
            <textarea
              value={editArgs}
              onChange={(e) => setEditArgs(e.target.value)}
              rows={5}
              className="w-full px-3 py-2 rounded-md bg-slate-950 border border-slate-700 text-xs font-mono focus:outline-none focus:border-indigo-500"
            />
          </div>
        </div>
        <div className="px-5 py-4 border-t border-slate-800 flex justify-end gap-2">
          <button
            onClick={() => onDecide("reject")}
            className="px-4 py-2 rounded-md border border-slate-700 text-slate-300 hover:bg-slate-800 text-sm"
          >
            Reject
          </button>
          <button
            onClick={() => onDecide("edit")}
            className="px-4 py-2 rounded-md border border-indigo-500/40 text-indigo-300 hover:bg-indigo-500/10 text-sm"
          >
            Edit
          </button>
          <button
            onClick={() => onDecide("approve")}
            className="px-4 py-2 rounded-md bg-emerald-600 hover:bg-emerald-500 text-white text-sm font-medium"
          >
            Approve
          </button>
        </div>
      </div>
    </div>
  );
}

// web/frontend-vue/src/pages/Run.vue
<script setup lang="ts">
// dev 全链路 + 审批握手页。迁移自 DevPilot Run.tsx（状态机 + RunSocket + 三态审批）。
import { computed, onUnmounted, ref } from 'vue'
import { Play } from 'lucide-vue-next'
import { RunSocket, type AuditEntry, type BlackboardData, type DoneSummary, type ServerFrame } from '../api'

type Status = 'idle' | 'connecting' | 'running' | 'awaiting_approval' | 'done' | 'error'

const task = ref('')
const status = ref<Status>('idle')
const audit = ref<AuditEntry[]>([])
const blackboard = ref<BlackboardData | null>(null)
const approval = ref<{ action: string; args: Record<string, unknown>; reason: string } | null>(null)
const summary = ref<DoneSummary | null>(null)
const decisionComment = ref('')
const editArgs = ref('')
let socket: RunSocket | null = null

const EVENT_COLORS: Record<string, string> = {
  agent_step: '#6366f1',
  llm_call: '#a855f7',
  tool_call: '#10b981',
  approval: '#f5a623',
}

const STATUS_STYLES: Record<Status, { color: string; label: string }> = {
  idle: { color: 'var(--cf-text-3)', label: 'idle' },
  connecting: { color: 'var(--cf-amber)', label: 'connecting' },
  running: { color: 'var(--cf-bili-blue)', label: 'running' },
  awaiting_approval: { color: 'var(--cf-amber)', label: 'awaiting approval' },
  done: { color: 'var(--cf-green)', label: 'done' },
  error: { color: 'var(--cf-red)', label: 'error' },
}

const statusBadge = computed(() => STATUS_STYLES[status.value])
const canStart = computed(() => status.value === 'idle' || status.value === 'done' || status.value === 'error')

function onStart(): void {
  const t = task.value.trim()
  if (!t || !canStart.value) return
  audit.value = []
  blackboard.value = null
  approval.value = null
  summary.value = null
  status.value = 'connecting'
  const sock = new RunSocket({
    onOpen: () => {
      sock.send({ task: t })
      status.value = 'running'
    },
    onFrame: (f: ServerFrame) => handleFrame(f),
    onClose: () => {
      if (status.value === 'running') status.value = 'done'
    },
    onError: () => {
      status.value = 'error'
    },
  })
  socket = sock
  sock.connect()
}

function handleFrame(frame: ServerFrame): void {
  switch (frame.type) {
    case 'audit':
      audit.value.push(frame.entry)
      break
    case 'blackboard':
      blackboard.value = frame.data
      break
    case 'approval_request':
      approval.value = { action: frame.action, args: frame.args, reason: frame.reason }
      editArgs.value = JSON.stringify(frame.args, null, 2)
      decisionComment.value = ''
      status.value = 'awaiting_approval'
      break
    case 'done':
      blackboard.value = frame.blackboard
      summary.value = frame.summary
      approval.value = null
      status.value = 'done'
      socket?.close()
      break
  }
}

function sendDecision(decision: 'approve' | 'reject' | 'edit'): void {
  if (!approval.value || !socket) return
  let args = approval.value.args
  if (decision === 'edit') {
    try {
      args = JSON.parse(editArgs.value)
    } catch {
      alert('Edit args 不是合法 JSON')
      return
    }
  }
  socket.send({ decision, comment: decisionComment.value, args })
  approval.value = null
  status.value = 'running'
}

onUnmounted(() => socket?.close())
</script>

<template>
  <div class="run-page">
    <header class="run-header">
      <h1 class="grad-bili-text">编排运行</h1>
      <span class="status-badge" :style="{ color: statusBadge.color, borderColor: statusBadge.color }">
        {{ statusBadge.label }}
      </span>
    </header>

    <div class="run-form">
      <textarea
        v-model="task"
        placeholder="输入开发任务，如「新增一个计算器工具函数」"
        rows="2"
      />
      <button class="start-btn" :disabled="!canStart || !task.trim()" @click="onStart">
        <Play :size="15" /> 开始
      </button>
    </div>

    <div class="run-body">
      <!-- 左：Timeline -->
      <div class="timeline-col">
        <div class="panel-title">审计时间线</div>
        <div class="timeline">
          <div v-for="(e, i) in audit" :key="i" class="tl-item">
            <span class="tl-event" :style="{ color: EVENT_COLORS[e.event] || 'var(--cf-text-3)' }">● {{ e.event }}</span>
            <span class="tl-actor">{{ e.actor }}</span>
            <span class="tl-detail">{{ JSON.stringify(e.detail) }}</span>
            <span class="tl-meta">{{ e.timestamp }} · {{ e.trace_id }}</span>
          </div>
          <div v-if="audit.length === 0" class="empty-mini">无审计事件</div>
        </div>
      </div>

      <!-- 右：Blackboard -->
      <div class="bb-col">
        <div class="panel-title">黑板</div>
        <div class="bb-grid">
          <div class="bb-panel">
            <div class="bb-label">Plan</div>
            <pre class="bb-pre">{{ (blackboard?.plan ?? []).join('\n') }}</pre>
          </div>
          <div class="bb-panel">
            <div class="bb-label">Code Diff</div>
            <pre class="bb-pre emerald">{{ blackboard?.code_diff || '—' }}</pre>
          </div>
          <div class="bb-panel">
            <div class="bb-label">Review</div>
            <pre class="bb-pre">{{ blackboard?.review || '—' }}</pre>
          </div>
          <div class="bb-panel">
            <div class="bb-label">Test Result</div>
            <pre class="bb-pre">{{ blackboard?.test_result || '—' }}</pre>
          </div>
        </div>
        <div v-if="summary" class="bb-summary">
          <span class="bb-sum-label">总事件 {{ summary.total_events }}</span>
          <span v-for="(c, k) in summary.by_event" :key="k" class="bb-tag">{{ k }}: {{ c }}</span>
        </div>
      </div>
    </div>

    <!-- 审批模态 -->
    <div v-if="approval" class="modal-mask">
      <div class="modal-card">
        <h2 class="modal-title">审批请求</h2>
        <div class="modal-row"><span class="mr-label">Action</span><span class="mr-value">{{ approval.action }}</span></div>
        <div class="modal-row"><span class="mr-label">Reason</span><span class="mr-value">{{ approval.reason }}</span></div>
        <div class="modal-args">
          <div class="mr-label">Args（可编辑）</div>
          <textarea v-model="editArgs" rows="8" class="args-input" />
        </div>
        <input v-model="decisionComment" placeholder="Comment（可选）" class="comment-input" />
        <div class="modal-actions">
          <button class="btn-reject" @click="sendDecision('reject')">Reject</button>
          <button class="btn-edit" @click="sendDecision('edit')">Edit</button>
          <button class="btn-approve" @click="sendDecision('approve')">Approve</button>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
.run-page {
  height: 100%;
  display: flex;
  flex-direction: column;
}
.run-header {
  display: flex;
  align-items: center;
  gap: 12px;
  padding: 14px 24px;
  border-bottom: 1px solid var(--cf-border);
}
.run-header h1 {
  font-size: 18px;
  margin: 0;
}
.status-badge {
  font-size: 12px;
  padding: 2px 10px;
  border: 1px solid;
  border-radius: 99px;
}
.run-form {
  display: flex;
  gap: 12px;
  padding: 16px 24px;
  border-bottom: 1px solid var(--cf-border);
}
.run-form textarea {
  flex: 1;
  padding: 10px 14px;
  border-radius: 10px;
  background: var(--cf-card);
  border: 1px solid var(--cf-border);
  color: var(--cf-text-1);
  font-size: 14px;
  font-family: inherit;
  resize: none;
}
.start-btn {
  display: flex;
  align-items: center;
  gap: 6px;
  padding: 10px 20px;
  border-radius: 10px;
  background: var(--cf-bili-blue);
  color: #fff;
  border: none;
  cursor: pointer;
  font-size: 14px;
}
.start-btn:disabled {
  background: var(--cf-hover);
  color: var(--cf-text-4);
  cursor: not-allowed;
}
.run-body {
  flex: 1;
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 1px;
  background: var(--cf-border);
  min-height: 0;
}
.timeline-col,
.bb-col {
  background: var(--cf-bg);
  display: flex;
  flex-direction: column;
  min-height: 0;
}
.panel-title {
  padding: 10px 16px;
  font-size: 11px;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  color: var(--cf-text-3);
  border-bottom: 1px solid var(--cf-border);
}
.timeline {
  flex: 1;
  overflow-y: auto;
  padding: 12px 16px;
}
.tl-item {
  display: flex;
  flex-direction: column;
  gap: 2px;
  padding: 8px 0;
  border-bottom: 1px solid var(--cf-border-soft);
}
.tl-event {
  font-size: 13px;
  font-weight: 600;
}
.tl-actor {
  font-size: 12px;
  color: var(--cf-text-2);
}
.tl-detail {
  font-size: 11px;
  font-family: ui-monospace, monospace;
  color: var(--cf-text-3);
  word-break: break-all;
}
.tl-meta {
  font-size: 10px;
  color: var(--cf-text-4);
}
.empty-mini {
  color: var(--cf-text-4);
  font-size: 13px;
  padding: 16px 0;
}
.bb-grid {
  flex: 1;
  display: grid;
  grid-template-columns: 1fr 1fr;
  grid-template-rows: 1fr 1fr;
  gap: 1px;
  background: var(--cf-border);
  min-height: 0;
}
.bb-panel {
  background: var(--cf-bg);
  display: flex;
  flex-direction: column;
  min-height: 0;
}
.bb-label {
  padding: 8px 12px;
  font-size: 11px;
  color: var(--cf-text-3);
  border-bottom: 1px solid var(--cf-border);
}
.bb-pre {
  flex: 1;
  margin: 0;
  padding: 10px 12px;
  overflow: auto;
  font-size: 12px;
  font-family: ui-monospace, monospace;
  color: var(--cf-text-2);
  white-space: pre-wrap;
}
.bb-pre.emerald {
  color: var(--cf-green);
}
.bb-summary {
  padding: 10px 12px;
  border-top: 1px solid var(--cf-border);
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
  align-items: center;
}
.bb-sum-label {
  font-size: 12px;
  font-weight: 600;
  color: var(--cf-text-1);
}
.bb-tag {
  font-size: 11px;
  padding: 2px 8px;
  border-radius: 99px;
  background: var(--cf-hover);
  color: var(--cf-text-2);
}
.modal-mask {
  position: fixed;
  inset: 0;
  background: rgba(0, 0, 0, 0.6);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 50;
}
.modal-card {
  width: 560px;
  max-height: 80vh;
  overflow: auto;
  background: var(--cf-card);
  border: 1px solid var(--cf-border);
  border-radius: var(--cf-radius-lg);
  padding: 24px;
  display: flex;
  flex-direction: column;
  gap: 12px;
}
.modal-title {
  font-size: 18px;
  margin: 0;
}
.modal-row {
  display: flex;
  gap: 8px;
  font-size: 13px;
}
.mr-label {
  color: var(--cf-text-3);
  min-width: 60px;
}
.mr-value {
  color: var(--cf-text-1);
  word-break: break-all;
}
.modal-args {
  display: flex;
  flex-direction: column;
  gap: 6px;
}
.args-input {
  padding: 10px;
  border-radius: 8px;
  background: var(--cf-bg);
  border: 1px solid var(--cf-border);
  color: var(--cf-text-1);
  font-family: ui-monospace, monospace;
  font-size: 12px;
  resize: vertical;
}
.comment-input {
  padding: 10px 12px;
  border-radius: 8px;
  background: var(--cf-bg);
  border: 1px solid var(--cf-border);
  color: var(--cf-text-1);
  font-size: 13px;
}
.modal-actions {
  display: flex;
  justify-content: flex-end;
  gap: 10px;
}
.modal-actions button {
  padding: 8px 18px;
  border-radius: 8px;
  font-size: 13px;
  cursor: pointer;
  border: 1px solid;
}
.btn-reject {
  background: transparent;
  border-color: var(--cf-red);
  color: var(--cf-red);
}
.btn-edit {
  background: transparent;
  border-color: var(--cf-bili-blue);
  color: var(--cf-bili-blue);
}
.btn-approve {
  background: var(--cf-green);
  border-color: var(--cf-green);
  color: #fff;
}
</style>
